### ISSUE TITLE
Application logging exercise doesn't render the command to extract the POD name correctly

### ISSUE THREAD

**Issue by dsyer** [eduk8s-labs/lab-k8s-fundamentals#1] opened 2020-04-20 09:16 UTC
In this file: `workshop/content/exercises/10-application-logging.md`, I see

```
POD=`kubectl get pod -l app=blog -o template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}' | head -1` && echo $POD
```

If I copy that and run it in a terminal it works. But it renders in eduk8s as 

```
POD=`kubectl get pod -l app=blog -o template --template '\n' | head -1` && echo $POD
```

(the template is mangled/omitted). I guess it needs to be escaped in some way?

**Comment by dsyer** [comment] 2020-04-20 09:30
Same thing in step 16 "Setting up Database"

**Comment by GrahamDumpleton** [comment] 2020-04-20 09:32
Was caused by recently turning on Liquid rendering engine as default rather than option. Thus need to surround section with:

```
{% raw %}
...
{% endraw %}
```

Fixed in both cases.

**Closed by GrahamDumpleton** 2020-04-20 09:32 UTC
